import random

from pygame import Color

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 480
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
BG_COLOR = Color("Black")

CIR_CENTER = (SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2)
CIR_RAD = 10
CIR_COLOR = Color("White")
CIR_X_START_MOVE = random.choice([0, 1])
CIR_Y_START_MOVE = random.choice([0, 1])
CIR_SPEED = 1

DESKS_WIDTH = 10
DESKS_HEIGHT = 60
DESKS_START_POS_X = (30, SCREEN_WIDTH - DESKS_WIDTH - 30)
DESKS_START_POS_Y = SCREEN_HEIGHT // 2 - DESKS_HEIGHT
DESKS_COLOR = Color("White")
DESKS_SPEED = 1

COUNTER_FONT_SIZE = 26
COUNTER_FONT_COLOR = Color("Yellow")
COUNTER_X = SCREEN_WIDTH // 2 - COUNTER_FONT_SIZE * 5
COUNTER_Y = SCREEN_HEIGHT // 2 - COUNTER_FONT_SIZE

GAME_SPEED = 10
